Spelling
ImageMagick/ImageMagick pull request #5787
Opened 2022-11-22 04:14 UTC by jsoref

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/ImageMagick/ImageMagick/pulls) open
- [x] I have verified that I am following the existing coding patterns and practices as demonstrated in the repository.

### Description

This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

Note: I'll try to annotate the changes. For medium size PRs, I tend to be asked to split them -- I can do this according to project requests -- my general preference is by directory/file type -- it's very expensive for me to split by "is comment" vs "is api" vs "is function", although it is doable (it just takes longer and is generally more fragile as I tend to squash and then select which means that later adjustments are much harder). In general, I prefer to drop problematic changes first (before squashing).

The misspellings have been reported at https://github.com/jsoref/ImageMagick/commit/b59c962bd0e91d1533fcc0b089ab75869abcfe3f#commitcomment-90677150

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/ImageMagick/commit/066cbc34c59a678049650598a950a5ec1e959bb5

Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

2022-11-22 05:00 UTC, jsoref commented on www/cite.html
> +<pre class="bg-light text-dark mx-4"><samp>The ImageMagick Development Team, 2021. ImageMagick, Available at: https://imagemagick.org.</samp></pre>
notable

2022-11-22 05:01 UTC, jsoref commented on www/conjure.html
> +    <td>value="double", operator="Add, And, Divide, LeftShift, Max, Min, Multiply, Or, Rightshift, Subtract, Xor", channel="All, Default, Alpha, Black, Blue, CMYK, Cyan, Gray, Green, Index, Magenta,
this isn't a spelling fix... it just looked odd...

2022-11-22 05:13 UTC, jsoref commented on www/source/english.xml
> +        <message name="CurlyBracesNestedTooDeeply">
notable. these changes presumably break localizations -- each project has a different policy about localizations, it's a toss up between "please update" and "please don't touch"...

2022-11-22 05:13 UTC, jsoref commented on www/support.html
> +<p>For direct monetary contributions, click on the donate button to contribute thru PayPal or with a credit card:</p>
brands

2022-11-22 07:01 UTC, dlemstra commented on Magick++/lib/Magick++/Image.h
> +    // a polynomial function to apply to the image.
@fmw42 Can you confirm?

2022-11-22 07:05 UTC, dlemstra commented on MagickCore/cache.c
> +%  completely replaced without need to refer to their preexisting values.
@fmw42 Can you confirm this change? pre-existing looks okay to me?

2022-11-22 07:09 UTC, dlemstra commented on MagickCore/display.c
> +  RegionOfInterestCommand,
Don't think we can make this change. Can you confirm @urban-warrior?

2022-11-22 07:10 UTC, dlemstra commented on MagickCore/distort.c
> +    case QuadrilateralDistortion:
Appears not to be used so safe to change.

2022-11-22 07:14 UTC, dlemstra requested changes
It would be a lot easier to review and merge this changes if it would be split up in smaller PR's. Can you please create a separate pull request for the following folders?

- Magick++
- MagickCore
- MagickWand
- PerlMagick
- coders
- www
- rest/remaining

2022-11-22 11:20 UTC, urban-warrior commented on MagickCore/display.c
> +  RegionOfInterestCommand,
An ENUM that is not in a public header, can be changed.  So changing RegionofInterestCommand is fine.

2022-11-22 13:18 UTC, jsoref commented
Sure. Hopefully tonight.

2022-11-24 21:38 UTC, dlemstra approved these changes

2022-11-25 08:59 UTC, merged